name: Fuzzing Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  fuzzing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t my-fuzzing-container -f ./Dockerfile  .

      - name: Run Docker Container
        run: docker run --rm my-fuzzing-container

