name: Fuzzing Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  fuzzing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t my-fuzzing-container -f ./Dockerfile  .

      - name: Run Docker Container
        run: docker run -d --name fuzzer-container my-fuzzing-container

      - name: Create Artifacts dir
        run: mkdir -p fuzz_results

      - name: container debug print
        run: docker exec fuzzer-container ls -la

      - name: container copy
        run: docker cp fuzzer-container:/fuzzing.log ./fuzz_results/output.log

      - name: Upload Fuzzing Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fuzzing-results
          path: fuzzing_results
